import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { HeaderSection } from "../sections/HeaderSection";
import { FooterSection } from "../sections/FooterSection";
import MainSection from "../sections/MainSection";
import { accountDataType } from "../src/types";

const Home: NextPage = () => {
  const [accountData, setAccountData] = useState<null | accountDataType>(null);

  return (
    <>
      <Head>
        <title>web3react Wallet Integration</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-screen flex flex-col">
        <HeaderSection accountData={accountData} />

        <MainSection setAccountData={setAccountData} />

        <FooterSection />
      </div>
    </>
  );
};

export default Home;
