import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>MetaMask Integration</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div style={{ display: "flex", alignItems: "center" }}>
          <Link href={"/"}>
            <a className="logo">🏡</a>
          </Link>

          <h2>Home</h2>
        </div>

        <Link href={"/mm"}>
          <a className="link">metamask</a>
        </Link>

        <Link href={"/w3r"}>
          <a className="link">web3react</a>
        </Link>

        <Link href={"/w3m"}>
          <a className="link">web3modal</a>
        </Link>
      </main>
    </>
  );
};

export default Home;
